library('R6')
library(RSQLite,verbose=FALSE)	# for database connection

source('server.config')

DB.Manager <- R6Class("DB.Manager")

DB.Manager$set("public","sqlite", NULL)
DB.Manager$set("public","dbConvert", NULL)
DB.Manager$set("public","gmtFiles", NULL)	
DB.Manager$set("public","OrgInfo", NULL)	# this field does not allow direct access, use 'QueryOrgInfo' to get org info
DB.Manager$set("public","Quotes", NULL)

## Init function
DB.Manager$set("public","initialize",
	function(){
		self$sqlite <- dbDriver("SQLite")
		
		self$dbConvert <- dbConnect( self$sqlite, paste0(CONFIG_DATA_DATAPATH, "convertIDs.db"), flags=SQLITE_RO) 
		
		self$gmtFiles = list.files(path = paste0(datapath,"pathwayDB"), pattern=".*\\.db")
		self$gmtFiles = paste(datapath, "pathwayDB/", gmtFiles,sep="")
		dbQueryResult <- dbGetQuery(self$dbConvert, paste("select distinct * from orgInfo " ))
		self$OrgInfo <- dbQueryResult[order(dbQueryResult$name),]

		TmpQuotes <- dbGetQuery(self$dbConvert, " select * from quotes")
		self$Quotes <- paste0("\"",TmpQuotes$quotes,"\"", " -- ",TmpQuotes$author,".       ")

	}
)

# find species information use id
DB.Manager$set("public", "findSpeciesById",
	function(speciesID){ 
		orgInfo <- self$OrgInfo
  		return( orgInfo[which(orgInfo$id == speciesID),]  )
	}
)


# find species name use id
DB.Manager$set("public", "findSpeciesNameById",
	function(speciesID){ 
		orgInfo <- self$OrgInfo
  		return( orgInfo[which(orgInfo$id == speciesID),3]  )
	}
)



# get id, ens, species from convertID mapping table
DB.Manager$set("public", "QuerySpeciesInfoFromConvertDBMapping",
	function(querySet){
		querySTMT <- paste( "select distinct id,ens,species from mapping where id IN ('", paste(querySet,collapse="', '"),"')",sep="")
		result <- dbGetQuery(self$dbConvert, querySTMT)
		return(result)
	}
)


#Find a query set of genes enriched with functional category
DB.Manager$set("public", "QueryGeneSetsFromPathway",
	function (converted, convertedData, GO, selectOrg, myrange) {
		idNotRecognized = as.data.frame("ID not recognized!")
		if(is.null(converted) ) return(idNotRecognized) # no ID 
		querySet <- rownames(convertedData)
		if(length(querySet) == 0) return(idNotRecognized )
		ix = grep(converted$species[1,1],self$gmtFiles)
		if (length(ix) == 0 ) {return(idNotRecognized )}
		
		# If selected species is not the default "bestMatch", use that species directly
		if(selectOrg != "BestMatch") {  
			ix = grep(self$findSpeciesById(selectOrg)[1,1], self$gmtFiles )
			if (length(ix) == 0 ) {return(idNotRecognized )}
		}
		pathway <- dbConnect(self$sqlite, self$gmtFiles[ix], flags=SQLITE_RO)
		
		if(is.null(GO) ) GO <- "GOBP"   # initial value not properly set; enforcing  

		# get Gene sets
		querySet = rownames(convertedData)
		sqlQuery = paste( " select distinct gene,pathwayID from pathway where gene IN ('", paste(querySet,collapse="', '"),"')" ,sep="")
		# cat(paste0("\n\nhere:",GO,"There"))

		if( GO != "All") sqlQuery = paste0(sqlQuery, " AND category ='",GO,"'")
		result <- dbGetQuery( pathway, sqlQuery  )
		if( dim(result)[1] ==0) {return(list( x=as.data.frame("No matching species or gene ID file!" )) )}
		# list pathways and frequency of genes
		pathwayIDs = aggregate( result$pathwayID, by   = list(unique.values = result$pathwayID), FUN = length)
		pathwayIDs = pathwayIDs[which(pathwayIDs[,2]>= myrange[1] ),]
		pathwayIDs = pathwayIDs[which( pathwayIDs[,2] <= myrange[2] ),]
		if(dim(pathwayIDs)[1] ==0 ) geneSets = NULL;
		
		# convert pathways into lists like those generated by readGMT
		geneSets = lapply(pathwayIDs[,1], function(x)  result[which(result$pathwayID == x ),1]     )
		pathwayInfo <- dbGetQuery( pathway, paste( " select distinct id,Description from pathwayInfo where id IN ('", 
								paste(pathwayIDs[,1],collapse="', '"),   "') ",sep="") )
		ix = match( pathwayIDs[,1], pathwayInfo[,1])
		names(geneSets) <- pathwayInfo[ix,2]  
		#geneSets <- geneSets[ -which(duplicated(names(geneSets) ))] # remove geneSets with the same name
		dbDisconnect(pathway)
		return( geneSets )
	}
} 



