---
title: "test_workflow_doc"
output:
  html_document: default
  pdf_document: default
params:
  YOUR_DATA_PATH:
    label: Data
    value: F:/data104b_final/data_go/GSE37704_sailfish_genecounts.csv
    input: file
  YOUR_EXPERIMENT_PATH:
    label: Design
    value: null
    input: file
  data_file_format:
    label: "Format"
    value: 2
    input: radio
    choices: [1,2,3] 
  no_id_conversion:
    label: "Do not convert to ensembl"
    value: FALSE
    input: checkbox
  min_counts:
    label: "min PCM"
    value: .5
    input: numeric
  n_min_samples_count:
    label: "n libaries"
    value: 1
    input: numeric
  counts_transform:
    label: "Transform counts data for clustering & PCA."
    value: 1
    input: radio
    choices: [edgeR, vst, rlog]
  counts_log_start:
    label: "psuedocount"
    value: 4
    input: numeric
  log_transform_fpkm:
    label: "(Normalized Expression) Log transform?"
    value: NULL
    input: radio
    choiceNames: ["No", "Yes"]
    choiceValues: [FALSE, TRUE]
  log_start_fpkm:
    label: "(Normalized Expression) Constant c for started log(x+c)"
    value: 3
    input: numeric
  low_filter_fpkm:
    label: "(Normalized Expression) fpkm Minimum level"
    value: 4
    input: numeric
  n_min_samples_fpkm:
    label: "(Normalized Expression) Minimum Samples"
    value: 5
    input: numeric
  missing_value:
    label: "missing value imputation"
    value: geneMedian
    input: select
    choices: ["geneMedian", "treatAsZero", "geneMedianInGroup"]
  scatter_x:
    label: "X axis"
    value: ""
    input: text
  scatter_y:
    label: "Y axis"
    value: ""
    input: text
  sd_color:
    label: "SD_vs_mean"
    value: "Red"
    input: text
  rank:
    label: "Use mean of Rank values"
    value: False
    input: checkbox
  no_fdr:
    label: "[LFC] No P values"
    value: FALSE
    input: checkbox
  date:
    label: "Date: "
    value: !r Sys.Date()
  printcode:
    label: "Display Code"
    value: TRUE
    input: checkbox
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = params$printcode)
```
<!-- Select the drop down menu for the "Knit" button and select "Knit with parameters" to knit this document. -->

# Print All Selections
```{r}
for (i in 1:length(params)){
  if( TRUE)
    cat(paste0(names(params)[i], ": ", params[[i]], "\n"))
}
```



```{r}
devtools::load_all()
```

# LOAD DATA FUNCTIONS

```{r Create Data Paths}

idep_data <- idepGolem::get_idep_data()

expression_file <- data.frame(
  datapath = params$YOUR_DATA_PATH
)
if(!is.null(params$YOUR_EXPERIMENT_PATH))
experiment_file <- data.frame(
  datapath = params$YOUR_EXPERIMENT_PATH
) else{
  experiment_file <- NULL
}
```

```{r Create2}
load_data <- input_data(
  expression_file = expression_file,
  experiment_file = experiment_file,
  go_button = FALSE,
  demo_data_file = idep_data$demo_data_file,
  demo_metadata_file = idep_data$demo_metadata_file
)

converted <- convert_id(
  query = rownames(load_data$data),
  idep_data = idep_data,
  select_org = "BestMatch"
)

all_gene_info <- gene_info(
  converted = converted,
  select_org = "BestMatch",
  idep_data = idep_data
)

converted_data <- convert_data(
  converted = converted,
  no_id_conversion = params$no_id_conversion,
  data = load_data$data
)

gene_names <- get_all_gene_names(
  mapped_ids = converted_data$mapped_ids,
  all_gene_info = all_gene_info
)

```


## PRE-PROCESS FUNCTIONS

```{r Pre-Process Data}

processed_data <- pre_process(
  data = converted_data$data,
  missing_value = params$missing_value,
  data_file_format = params$data_file_format,
  low_filter_fpkm = params$low_filter_fpkm,
  n_min_samples_fpkm = params$n_min_samples_fpkm,
  log_transform_fpkm = params$log_transform_fpkm,
  log_start_fpkm = params$log_start_fpkm,
  min_counts = params$min_counts,
  n_min_samples_count = params$n_min_samples_count,
  counts_transform = params$counts_transform,
  counts_log_start = params$counts_log_start,
  no_fdr = params$no_fdr
)
# processed_data <- pre_process(
#   data = converted_data$data,
#   missing_value = "geneMedian",
#   data_file_format = 1,
#   low_filter_fpkm = NULL,
#   n_min_samples_fpkm = NULL,
#   log_transform_fpkm = NULL,
#   log_start_fpkm = NULL,
#   min_counts = .5,
#   n_min_samples_count = 1,
#   counts_transform = 1,
#   counts_log_start = 4,
#   no_fdr = NULL
# )
```

fig.height=1.5, fig.width=2.5
```{r}
if(params$data_file_format == 1){
 total_counts_ggplot(
  counts_data = processed_data$raw_counts,
  sample_info = load_data$sample_info
) 
}

```


```{r fig.height=5.5, fig.width=7.5}
#colnames(processed_data$data)

eda_scatter(
  processed_data = processed_data$data,
  #plot_xaxis = "p53_IR_1",
  #plot_yaxis = "p53_mock_1"
  plot_yaxis = colnames(processed_data$data)[1],
  plot_xaxis = colnames(processed_data$data)[2]
)
```



```{r fig.height=5.5, fig.width=7.5}
eda_boxplot(
  processed_data = processed_data$data,
  sample_info = load_data$sample_info
)
```